apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
  labels:
    app: nodeapp
spec:
  selector:
    app: nodeapp
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 4000 
  type: LoadBalancer 
